### ISSUE TITLE
Autoplay option is not working

### ISSUE THREAD

**Issue by AmitTurner** [rcaferati/react-awesome-slider#47]
hello! ive tried using the autoplay option according to the docs([https://caferati.me/demo/react-awesome-slider/autoplay](https://caferati.me/demo/react-awesome-slider/autoplay)), and im getting this error while trying to render:
![Inked66958717-77990b00-f071-11e9-8f0e-4f11462a12f5_LI](https://user-images.githubusercontent.com/19940028/67249433-5587fa00-f470-11e9-81aa-cc5b651f4849.jpg)

ive tried looking at the example page code as well but there all the logic is outside of the actual package, so im wondering if the autoplay option exist?

in the 1.x version ive used the autoplay suggested here but it sometimes crash on mobile when moving across images fast.

thank you.

**Comment by rcaferati** [comment]
Hi @AmitTurner! What are you using for building your project?

**Comment by topovik** [comment]
Hi, exactly the same error, Next.js

**Comment by AmitTurner** [comment]
> Hi @AmitTurner! What are you using for building your project?

Im using create-react-app, no special configs.

**Comment by ukor** [comment]
Any luck with fix this?

**Comment by rcaferati** [comment]
Hey guys! I've updated the docs aiming to reduce a bit the confusion over the usage of the Autoplay HOC. You can check it [here](https://github.com/rcaferati/react-awesome-slider#using-the-autoplay-hoc-with-plain-css).

The CSS is now on the main bundle and the HOC is also explicitly exported to the dist folder and you can use it directly from there. Something like:

```
import AwesomeSlider from 'react-awesome-slider';
import withAutoplay from 'react-awesome-slider/dist/autoplay';
import 'react-awesome-slider/dist/styles.css';

const AutoplaySlider = withAutoplay(AwesomeSlider);

const slider = (
  <AutoplaySlider
    play={true}
    cancelOnInteraction={false} // should stop playing on user interaction
    interval={6000}
  >
    <div>1</div>
    <div>2</div>
    <div>3</div>
  </AutoplaySlider>
);
```

**Comment by ukor** [comment]
@rcaferati Thanks for your help. Here is my code and the autoslider still does not work
```
import React from 'react';
// import styled from 'styled-components';
import AwesomeSlider from 'react-awesome-slider';
import withAutoplay from 'react-awesome-slider/dist/autoplay';
import 'react-awesome-slider/dist/styles.css';

const AutoplaySlider = withAutoplay(AwesomeSlider);

// const Wrapper = styled.div``;

function Carousel() {
    return (
        <AutoplaySlider
                play={true}
                interval={5000}
                cancelOnInteraction={false}
            >
                <div>1</div>
                <div>2</div>
                <div>3</div>
            </AutoplaySlider>
    );
}

export default Carousel;

```

It just stays on the first slide.

**Comment by rcaferati** [comment]
@ukor which kind of error are you getting?

**Comment by ukor** [comment]
There are no errors on the console. Just a warning that `componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.`

but when the arrow button is clicked a TypeError is thrown `Uncaught TypeError: Cannot read property 'clearCssEndEvent' of null`

**Comment by rcaferati** [comment]
@ukor Interesting! Can you check which version of the `react-awesome-slider` library are you using?

**Comment by ukor** [comment]
@rcaferati v2.1.1

**Comment by rcaferati** [comment]
@ukor Try cleaning up your `node_modules` folder and installing `v2.1.2`. BTW which browser are you testing it on?

**Comment by ukor** [comment]
@rcaferati I just installed `v2.1.2`, still no luck. I am using Google Chrome `Version 78.0.3904.87`

**Comment by rcaferati** [comment]
@ukor Can you provide a public link for me to access it or a snippet of the code that's being used? The error that you've mentioned earlier is related to the `wac` dependency not being loaded.

**Comment by AmitTurner** [comment]
hey @rcaferati ! after the latest update theres a big progress. thank you! it loads now but there is one last issue.
it only autoplay after i click on the right arrow first, it wont show the top progress bar or start transitioning unless i first move the first "image" myself.
i used your example code. anyway to make it autoplay completely as in your website?

**Comment by rcaferati** [comment]
@AmitTurner Good one! It was waiting for the startupScreen to start the autoplay. Try it out on `v2.1.3`

**Comment by milind2945** [comment]
@rcaferati Awesome work 
Kudos
